apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  name: test-reference
  decription: test-reference
  tags:
    - component
    - service
    - test
  links:
    - url: https://joshidipesh12.github.io
      title: My Portfolio Website
      icon: dashboard
    - url: https://github.com/joshidipesh12/joshidipesh12.github.io
      title: Github Source
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  providesApis:
    - test-api-ref