apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: default
  annotations:
    backstage.io/source-location: url:https://github.com/joshidipesh12/joshidipesh12.github.io
  name: test-api-ref
  description: test-api-ref
  tags:
    - api
    - service
    - test
  links:
    - url: https://joshidipesh12.github.io
      title: My Portfolio Website
      icon: dashboard
relations:
  - type: apiProvidedBy
    targetRef: component:default/test-reference
    target:
      kind: component
      namespace: default
      name: test-reference
  - type: ownedBy
    targetRef: group:default/team-a
    target:
      kind: group
      namespace: default
      name: team-a
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
  definition: |
  swagger: '2.0.0'
  info:
    description: Service Description - TODO override ApiInfo bean to populate your own
      service name, description etc
    version: '2.0.0'
    title: Service API
    termsOfService: terms of service
    contact:
      name: Contact Team Name
      url: Contact Url
      email: Contact Email
    license:
      name: Licence Type
      url: License URL
  host: localhost:8090
  basePath: "/fxrs-service"
  tags:
    - name: fxrs-controller
      description: Fxrs Controller
    - name: service-controller
      description: Service Controller
  paths:
    "/v1/active-currency-list":
      get:
        tags:
          - fxrs-controller
        summary: Returns a list of active currencies - list of active and valid currency
          code and currency name
        operationId: getActiveCurrencyListUsingGET
        produces:
          - "*/*"
        responses:
          '200':
            description: "<b>OK</b>, returns the list of active and valid currency code
              and currency name."
            schema:
              type: array
              items:
                "$ref": "#/definitions/Currency"
          '401':
            description: "<b>Unauthorized</b> : <i>authentication token</i> empty, invalid
              or expired"
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
    "/v1/all-fxrates-by-base-currency/{fxrateCategory}/{date}/{baseCurrency}":
      get:
        tags:
          - FXRS Controller
        summary: Returns all FX rates for a given base currency, effective date, and
          rate type
        operationId: getAllFxRatesByBaseCurrencyUsingGET
        produces:
          - application/json
        parameters:
          - name: baseCurrency
            in: path
            description: Base currency
            required: false
            type: string
          - name: date
            in: path
            description: Effective date
            required: false
            type: string
          - name: fxrateCategory
            in: path
            description: FX Rate Category
            required: false
            type: string
        responses:
          '200':
            description: OK
            schema:
              "$ref": "#/definitions/FxRates"
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
    "/v1/current-fxrates":
      post:
        tags:
          - FXRS Controller
        summary: Returns current FX rates
        operationId: getCurrentFxRatesUsingPOST
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - in: body
            name: currencyPairs
            description: currencyPairs
            required: false
            schema:
              type: object
              additionalProperties:
                type: array
                items:
                  "$ref": "#/definitions/CurrencyPair"
        responses:
          '200':
            description: OK
            schema:
              "$ref": "#/definitions/FxRates"
          '201':
            description: Created
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
    "/v1/current-fxrates-by-base-currency/{currencyCode}":
      get:
        tags:
          - FXRS Controller
        summary: Returns current exchange rates for a given base currency
        operationId: getCurrentFxRatesByBaseCurrencyUsingGET
        produces:
          - "*/*"
        parameters:
          - name: currencyCode
            in: path
            description: ISO code for the base currency
            required: false
            type: string
        responses:
          '200':
            description: OK
            schema:
              "$ref": "#/definitions/FxRates"
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
    "/v1/current-fxrates-by-target-currency/{currencyCode}":
      get:
        tags:
          - FXRS Controller
        summary: Returns current exchange rates for a given target currency
        operationId: getCurrentFxRatesByTgtCurrencyUsingGET
        produces:
          - "*/*"
        parameters:
          - name: currencyCode
            in: path
            description: ISO code for the target currency
            required: false
            type: string
        responses:
          '200':
            description: OK
            schema:
              "$ref": "#/definitions/FxRates"
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
    "/v1/echo":
      post:
        tags:
          - service-controller
        summary: echo
        operationId: echoUsingPOST
        consumes:
          - application/json
        produces:
          - application/json;charset=utf-8
        parameters:
          - in: body
            name: request
            description: The product to be echoed
            required: false
            schema:
              "$ref": "#/definitions/Product"
        responses:
          '200':
            description: OK
            schema:
              "$ref": "#/definitions/Product"
          '201':
            description: Created
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
    "/v1/fxrate-category-versions":
      get:
        tags:
          - fxrs-controller
        summary: FXRS category version
        operationId: getFxRateCategoryVersionsUsingGET
        produces:
          - "*/*"
        responses:
          '200':
            description: "<b>OK</b>, returns the version for the currency conversion
              data. It will change daily(no fixed time) once the latest currency conversion
              data is available."
            schema:
              type: array
              items:
                "$ref": "#/definitions/UpdateDetail"
          '401':
            description: "<b>Unauthorized</b> : <i>authentication token</i> empty, invalid
              or expired"
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
    "/v1/fxrs-service":
      post:
        tags:
          - service-controller
        summary: search product by name
        operationId: searchByNameUsingPOST
        consumes:
          - application/json
        produces:
          - application/json;charset=utf-8
        parameters:
          - name: name
            in: query
            description: Name search criteria
            required: false
            type: string
            allowEmptyValue: false
        responses:
          '200':
            description: OK
            schema:
              type: array
              items:
                "$ref": "#/definitions/Product"
          '201':
            description: "<b>Created</b>, indicating that the submited creation request
              has successed. The response HTTP header <i>Location</i> contains the resource
              identifier."
            schema:
              type: array
              items:
                "$ref": "#/definitions/Product"
          '401':
            description: "<b>Unauthorized</b> : <i>authentication token</i> empty, invalid
              or expired"
          '403':
            description: Forbidden
          '404':
            description: Not Found
        deprecated: false
    "/v1/fxrs-service/{id}":
      get:
        tags:
          - service-controller
        summary: Get a product from its id
        operationId: searchByIdUsingGET
        produces:
          - application/json;charset=utf-8
        parameters:
          - name: id
            in: path
            description: Product identifier
            required: false
            type: string
        responses:
          '200':
            description: "<b>Found</b>."
            schema:
              "$ref": "#/definitions/Product"
          '401':
            description: "<b>Unauthorized</b> : <i>authentication token</i> empty, invalid
              or expired."
          '403':
            description: Forbidden
          '404':
            description: "<b>Not Found</b> : the resource does not exist."
        deprecated: false
  definitions:
    Currency:
      type: object
      properties:
        currency_code:
          type: string
          example: CAD
          description: ISO code of the currency
        currency_name:
          type: string
          example: Canadian Dollar
          description: Full name of the currency
        currency_precision:
          type: integer
          format: int32
          description: Decimal precision of the currency value
        numeric_code:
          type: integer
          format: int32
          description: Currency numeric code
      title: Currency
    CurrencyPair:
      type: object
      properties:
        base_currency_code:
          type: string
        target_currency_code:
          type: string
      title: CurrencyPair
    CurrencyUnit:
      type: object
      properties:
        code:
          type: string
        country_codes:
          type: array
          items:
            type: string
        decimal_places:
          type: integer
          format: int32
        numeric3_code:
          type: string
        numeric_code:
          type: integer
          format: int32
        pseudo_currency:
          type: boolean
        symbol:
          type: string
      title: CurrencyUnit
    FxRate:
      type: object
      properties:
        base_currency_code:
          type: string
          example: USD
          description: ISO code of the base currency
        effective_date:
          type: string
          format: date-time
          description: Date of when the rate takes effect
        rate:
          type: string
          description: FX Rate
        rate_type_code:
          type: string
          example: EOD
          description: Describes the type of exchange rate
          enum:
            - CUR
            - EOD
            - EOM
        target_currency_code:
          type: string
          example: CAD
          description: ISO code of the target currency
      title: FxRate
    FxRates:
      type: object
      properties:
        effective_date:
          type: string
          format: date-time
          description: Date of when the rates take effect
        fxrates:
          type: array
          description: List of exchange rates to add
          items:
            "$ref": "#/definitions/FxRate"
        version:
          type: integer
          format: int64
          description: FX rate version
      title: FxRates
    Money:
      type: object
      properties:
        amount:
          type: number
        amount_major:
          type: number
        amount_major_int:
          type: integer
          format: int32
        amount_major_long:
          type: integer
          format: int64
        amount_minor:
          type: number
        amount_minor_int:
          type: integer
          format: int32
        amount_minor_long:
          type: integer
          format: int64
        currency_unit:
          "$ref": "#/definitions/CurrencyUnit"
        minor_part:
          type: integer
          format: int32
        negative:
          type: boolean
        negative_or_zero:
          type: boolean
        positive:
          type: boolean
        positive_or_zero:
          type: boolean
        scale:
          type: integer
          format: int32
        zero:
          type: boolean
      title: Money
    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        categories:
          type: array
          description: The categories of the product
          items:
            type: string
        description:
          type: string
          description: The description of the product
        id:
          type: string
          description: General UUID
        name:
          type: string
          description: The name of the product
        price:
          description: The price of the product
          "$ref": "#/definitions/Money"
      title: Product
    UpdateDetail:
      type: object
      properties:
        effective_date:
          type: string
          description: FX rate effective date
        fx_rate_type_code:
          type: string
          example: EOD
          description: Describes the type of exchange rate
          enum:
            - CUR
            - EOD
            - EOM
        version:
          type: integer
          format: int64
          description: FX rate version
      title: UpdateDetail